// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEV3q05Q1PsBX7QtasoN-heRvtBFxC6tY',
    appId: '1:444186462890:web:4709e96f448033023fded3',
    messagingSenderId: '444186462890',
    projectId: 'evently-3168a',
    authDomain: 'evently-3168a.firebaseapp.com',
    storageBucket: 'evently-3168a.firebasestorage.app',
    measurementId: 'G-D3RC50F34Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYl2MlJpWWhuQI9EfuLvAjV9rsGD_i4ms',
    appId: '1:444186462890:android:571d0ae2ef0378563fded3',
    messagingSenderId: '444186462890',
    projectId: 'evently-3168a',
    storageBucket: 'evently-3168a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5aQR-Mz_Q8TWi3DHBTuyPtaL3fN63RjA',
    appId: '1:444186462890:ios:1ac80a2791e1fd3c3fded3',
    messagingSenderId: '444186462890',
    projectId: 'evently-3168a',
    storageBucket: 'evently-3168a.firebasestorage.app',
    iosBundleId: 'com.example.eventlyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5aQR-Mz_Q8TWi3DHBTuyPtaL3fN63RjA',
    appId: '1:444186462890:ios:1ac80a2791e1fd3c3fded3',
    messagingSenderId: '444186462890',
    projectId: 'evently-3168a',
    storageBucket: 'evently-3168a.firebasestorage.app',
    iosBundleId: 'com.example.eventlyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCEV3q05Q1PsBX7QtasoN-heRvtBFxC6tY',
    appId: '1:444186462890:web:839452728cd308583fded3',
    messagingSenderId: '444186462890',
    projectId: 'evently-3168a',
    authDomain: 'evently-3168a.firebaseapp.com',
    storageBucket: 'evently-3168a.firebasestorage.app',
    measurementId: 'G-QMHY1PB28X',
  );
}
